// Generated by config/scripts/fork-maintenance/generate-vue-language-server-manifest.mjs; do not edit.
import { VUE_LANGUAGE_SERVER_DIR_NAME } from '../../shared/code-navigation/code-navigation-types'
import type { NpmPackageSet } from './npm-package-set-installer'

// Hashes computed 2026-10-01 from npm tarballs checked against their sha512 integrity.
export const VUE_LANGUAGE_SERVER_PACKAGES: NpmPackageSet = {
  name: VUE_LANGUAGE_SERVER_DIR_NAME,
  version: '0.3.0+vue.3.3.11',
  packages: [
    {
      path: 'node_modules/@babel/helper-string-parser',
      url: 'https://registry.npmjs.org/@babel/helper-string-parser/-/helper-string-parser-7.29.7.tgz',
      sha256: '124565ecd300d7187973060ba6b1d1c4f296e55f0489ddfd6af794f516fed127',
      sizeBytes: 8383
    },
    {
      path: 'node_modules/@babel/helper-validator-identifier',
      url: 'https://registry.npmjs.org/@babel/helper-validator-identifier/-/helper-validator-identifier-7.29.7.tgz',
      sha256: '7a31904bc45f1bb232d5e5dd797d12296f4a27fb4bf0f6d517827700f997dc1f',
      sizeBytes: 14245
    },
    {
      path: 'node_modules/@babel/parser',
      url: 'https://registry.npmjs.org/@babel/parser/-/parser-7.29.9.tgz',
      sha256: '8f3b9fbc531e0c08e2c329cf1ff57bbe121e2d10061b65a05614a25b2255cc43',
      sizeBytes: 439123
    },
    {
      path: 'node_modules/@babel/types',
      url: 'https://registry.npmjs.org/@babel/types/-/types-7.29.8.tgz',
      sha256: '514a4ed09355fe1417f03e89c5a5f518745e2eb75a4069d25b55a3e7298069de',
      sizeBytes: 301854
    },
    {
      path: 'node_modules/@volar/language-core',
      url: 'https://registry.npmjs.org/@volar/language-core/-/language-core-2.4.28.tgz',
      sha256: '9634a2d697741a95af7a068a80ae740eadc655557df45f56175433cbc3cf9286',
      sizeBytes: 7461
    },
    {
      path: 'node_modules/@volar/source-map',
      url: 'https://registry.npmjs.org/@volar/source-map/-/source-map-2.4.28.tgz',
      sha256: '053ca21a007a04afd4acff3cc2181971a45315e0b78b4875700ec904cc6671a6',
      sizeBytes: 4390
    },
    {
      path: 'node_modules/@volar/typescript',
      url: 'https://registry.npmjs.org/@volar/typescript/-/typescript-2.4.28.tgz',
      sha256: '489fc8eb2c67da21636a9b8c4cbfe5f48a2100b177489868195e5872685ce96a',
      sizeBytes: 42634
    },
    {
      path: 'node_modules/@vscode/l10n',
      url: 'https://registry.npmjs.org/@vscode/l10n/-/l10n-0.0.18.tgz',
      sha256: 'f1c2dc897488595f6bb42121869f525c6c6a5f7c8dca550754199c3251ed7c5c',
      sizeBytes: 4548
    },
    {
      path: 'node_modules/@vtsls/language-server',
      url: 'https://registry.npmjs.org/@vtsls/language-server/-/language-server-0.3.0.tgz',
      sha256: 'f065ff01476d71395caad2647fb56539bb80131f37081767b2aeee8586cbc0c9',
      sizeBytes: 7677
    },
    {
      path: 'node_modules/@vtsls/language-service',
      url: 'https://registry.npmjs.org/@vtsls/language-service/-/language-service-0.3.0.tgz',
      sha256: '08a4e8db21dc3c9be7080952cd5226932f578512e71b0bf2fd81c7f8af9401c5',
      sizeBytes: 330172
    },
    {
      path: 'node_modules/@vtsls/vscode-fuzzy',
      url: 'https://registry.npmjs.org/@vtsls/vscode-fuzzy/-/vscode-fuzzy-0.1.0.tgz',
      sha256: '3a04faaa2b0df05b4ece5bc3ff4d2316023d661b028ab15d4aa3f2f13b2a7d8a',
      sizeBytes: 11523
    },
    {
      path: 'node_modules/@vue/compiler-core',
      url: 'https://registry.npmjs.org/@vue/compiler-core/-/compiler-core-3.5.43.tgz',
      sha256: '70b573e270ee99268a15cb5df28043d17a7061940a13605f447bba4e135f5737',
      sizeBytes: 146016
    },
    {
      path: 'node_modules/@vue/compiler-dom',
      url: 'https://registry.npmjs.org/@vue/compiler-dom/-/compiler-dom-3.5.43.tgz',
      sha256: '6aef009ad384ea23f257ad4320d8a947e5a13c55ba7c3be568055496843f9ac6',
      sizeBytes: 168195
    },
    {
      path: 'node_modules/@vue/language-core',
      url: 'https://registry.npmjs.org/@vue/language-core/-/language-core-3.3.11.tgz',
      sha256: '4854401ddc58a4b913fbf9cf70a3406d65aa41c7a11172ead1258107e10944c4',
      sizeBytes: 72790
    },
    {
      path: 'node_modules/@vue/shared',
      url: 'https://registry.npmjs.org/@vue/shared/-/shared-3.5.43.tgz',
      sha256: '759b4f863f44b01e115574fb7083b024ac5dd820b9a861aeff2cb554a87c70a8',
      sizeBytes: 23527
    },
    {
      path: 'node_modules/@vue/typescript-plugin',
      url: 'https://registry.npmjs.org/@vue/typescript-plugin/-/typescript-plugin-3.3.11.tgz',
      sha256: '164415a4132ea7817df2e2bc9eb4416ee4c847c0b746d3d1b66ff63d1855b1e3',
      sizeBytes: 14641
    },
    {
      path: 'node_modules/alien-signals',
      url: 'https://registry.npmjs.org/alien-signals/-/alien-signals-3.2.1.tgz',
      sha256: '925c9fd0ef2748c5b266eae7d2561b88d16e0666b2eb98208474cb009760e430',
      sizeBytes: 8546
    },
    {
      path: 'node_modules/entities',
      url: 'https://registry.npmjs.org/entities/-/entities-7.0.1.tgz',
      sha256: '554b7e2a79fa9eda0439714011fa42d77c6829842faa91e022070015bfd483a0',
      sizeBytes: 113587
    },
    {
      path: 'node_modules/estree-walker',
      url: 'https://registry.npmjs.org/estree-walker/-/estree-walker-2.0.2.tgz',
      sha256: '302931e539a9c5568d56634119290c4df9a7bde64a2f2dbc646d6013e3b03c58',
      sizeBytes: 8353
    },
    {
      path: 'node_modules/jsonc-parser',
      url: 'https://registry.npmjs.org/jsonc-parser/-/jsonc-parser-3.3.1.tgz',
      sha256: '4a0315b8671e7463bae7af7c142cdf19e9aa7ba39eb36dc2df383b8648e3cbc9',
      sizeBytes: 27354
    },
    {
      path: 'node_modules/lru-cache',
      url: 'https://registry.npmjs.org/lru-cache/-/lru-cache-6.0.0.tgz',
      sha256: '5ce40deb031cf6968f3832502a68f8d26be09764dc4f8fc07957a2fd7e8cdf5e',
      sizeBytes: 5788
    },
    {
      path: 'node_modules/muggle-string',
      url: 'https://registry.npmjs.org/muggle-string/-/muggle-string-0.4.1.tgz',
      sha256: '626315ee7cc1981c08139999aba9afa694b67aa9d659822f8b53b9e358278067',
      sizeBytes: 7359
    },
    {
      path: 'node_modules/path-browserify',
      url: 'https://registry.npmjs.org/path-browserify/-/path-browserify-1.0.1.tgz',
      sha256: '74ad6965c6f8cb61d17b1798d48095c3238eca5707b517640a12150f17b8f93d',
      sizeBytes: 12477
    },
    {
      path: 'node_modules/picomatch',
      url: 'https://registry.npmjs.org/picomatch/-/picomatch-4.0.7.tgz',
      sha256: '697b463be3cdbd9ffc8f4194fd5019a69ddf95875fb703d78b2b115cc9e740a8',
      sizeBytes: 24326
    },
    {
      path: 'node_modules/semver',
      url: 'https://registry.npmjs.org/semver/-/semver-7.5.2.tgz',
      sha256: '32f78290c12246206449f9a18cf3f7fab44828f06c17448b7e8954ff54ce0a9a',
      sizeBytes: 26617
    },
    {
      path: 'node_modules/source-map-js',
      url: 'https://registry.npmjs.org/source-map-js/-/source-map-js-1.2.2.tgz',
      sha256: '05c8cf8e7c3a6b56cada7668fe9342b10f4b625efc92aba9ba05b9e8fe4d71a3',
      sizeBytes: 36349
    },
    {
      path: 'node_modules/typescript',
      url: 'https://registry.npmjs.org/typescript/-/typescript-5.9.3.tgz',
      sha256: '10e108c9cf7d5f2879053dff18515fb405abf2ccef63eaaf017d9c571687a1d3',
      sizeBytes: 4377468
    },
    {
      path: 'node_modules/vscode-jsonrpc',
      url: 'https://registry.npmjs.org/vscode-jsonrpc/-/vscode-jsonrpc-9.0.3.tgz',
      sha256: '282d3d574a565ab9bea0af6518eadac91221dfd0cd55cfd308662b816a7920a7',
      sizeBytes: 37477
    },
    {
      path: 'node_modules/vscode-languageserver',
      url: 'https://registry.npmjs.org/vscode-languageserver/-/vscode-languageserver-9.0.1.tgz',
      sha256: '6cd7f463ae7872e588a4dd5ed5149475fe32e53517509a81e715eb0540602412',
      sizeBytes: 32720
    },
    {
      path: 'node_modules/vscode-languageserver-protocol',
      url: 'https://registry.npmjs.org/vscode-languageserver-protocol/-/vscode-languageserver-protocol-3.18.4.tgz',
      sha256: '76ff8f83f7f1bac53e351cd30740ff75610277b65b4043141d359660d88f0dcd',
      sizeBytes: 64345
    },
    {
      path: 'node_modules/vscode-languageserver-textdocument',
      url: 'https://registry.npmjs.org/vscode-languageserver-textdocument/-/vscode-languageserver-textdocument-1.0.15.tgz',
      sha256: '2a133b20d5c5b1ff6d8627c628807c28d771b8741c8c6fca2aef3dd77cac669c',
      sizeBytes: 8372
    },
    {
      path: 'node_modules/vscode-languageserver-types',
      url: 'https://registry.npmjs.org/vscode-languageserver-types/-/vscode-languageserver-types-3.18.4.tgz',
      sha256: '83c119b73d1895194087e9376d0916161b5550c210e9e892b65a3e04a43ea68e',
      sizeBytes: 79419
    },
    {
      path: 'node_modules/vscode-languageserver/node_modules/vscode-jsonrpc',
      url: 'https://registry.npmjs.org/vscode-jsonrpc/-/vscode-jsonrpc-8.2.0.tgz',
      sha256: '3da44531c398f1545074cb728e359a822f35b9f8ac7171c847f42f0728b9c7cb',
      sizeBytes: 35427
    },
    {
      path: 'node_modules/vscode-languageserver/node_modules/vscode-languageserver-protocol',
      url: 'https://registry.npmjs.org/vscode-languageserver-protocol/-/vscode-languageserver-protocol-3.17.5.tgz',
      sha256: '7473eb2d2163f3f8bea09644f9d803789a195e596b65d3946c4157e583e3ccc8',
      sizeBytes: 59008
    },
    {
      path: 'node_modules/vscode-languageserver/node_modules/vscode-languageserver-types',
      url: 'https://registry.npmjs.org/vscode-languageserver-types/-/vscode-languageserver-types-3.17.5.tgz',
      sha256: 'd673f9e7f8bbe51351be51c58f32d4dcfa97a670ebb86bc633368394c609cac0',
      sizeBytes: 71382
    },
    {
      path: 'node_modules/vscode-uri',
      url: 'https://registry.npmjs.org/vscode-uri/-/vscode-uri-3.2.0.tgz',
      sha256: '12fa4a47728ca404c3a679e351eda6c54030c8ed3dd9bc6762ab0be1bf04014b',
      sizeBytes: 59281
    },
    {
      path: 'node_modules/vue-component-meta',
      url: 'https://registry.npmjs.org/vue-component-meta/-/vue-component-meta-3.3.11.tgz',
      sha256: 'ad9cc61860a9ff8c13623ad7ffc27d66b2972c6014e01379500550593460d2c6',
      sizeBytes: 11635
    },
    {
      path: 'node_modules/yallist',
      url: 'https://registry.npmjs.org/yallist/-/yallist-4.0.0.tgz',
      sha256: 'a80c78aa276536615891ef66efbc17d3bd07c8cb14e3bd5298eed3006bfa4d49',
      sizeBytes: 4494
    }
  ]
}
