import type { SqlDialect } from '../../../../../shared/database/sql-dialect-lexing'

const COMMON_KEYWORDS = [
  'SELECT',
  'FROM',
  'WHERE',
  'AND',
  'OR',
  'NOT',
  'NULL',
  'IS',
  'IN',
  'EXISTS',
  'BETWEEN',
  'LIKE',
  'AS',
  'ON',
  'USING',
  'DISTINCT',
  'JOIN',
  'INNER JOIN',
  'LEFT JOIN',
  'RIGHT JOIN',
  'FULL JOIN',
  'CROSS JOIN',
  'GROUP BY',
  'ORDER BY',
  'HAVING',
  'ASC',
  'DESC',
  'UNION',
  'UNION ALL',
  'EXCEPT',
  'INTERSECT',
  'WITH',
  'CASE',
  'WHEN',
  'THEN',
  'ELSE',
  'END',
  'INSERT INTO',
  'VALUES',
  'UPDATE',
  'SET',
  'DELETE FROM',
  'CREATE TABLE',
  'CREATE VIEW',
  'CREATE INDEX',
  'ALTER TABLE',
  'DROP TABLE',
  'DROP VIEW',
  'PRIMARY KEY',
  'FOREIGN KEY',
  'REFERENCES',
  'DEFAULT',
  'BEGIN',
  'COMMIT',
  'ROLLBACK',
  'COUNT',
  'SUM',
  'AVG',
  'MIN',
  'MAX',
  'COALESCE',
  'CAST'
]

const DIALECT_KEYWORDS: Record<SqlDialect, readonly string[]> = {
  postgres: ['LIMIT', 'OFFSET', 'RETURNING', 'ILIKE', 'ON CONFLICT', 'EXPLAIN ANALYZE'],
  mysql: ['LIMIT', 'OFFSET', 'SHOW TABLES', 'DESCRIBE', 'ON DUPLICATE KEY UPDATE', 'EXPLAIN'],
  sqlserver: ['TOP', 'OFFSET', 'FETCH NEXT', 'ROWS ONLY', 'OUTPUT', 'MERGE', 'EXEC'],
  sqlite: ['LIMIT', 'OFFSET', 'RETURNING', 'PRAGMA', 'EXPLAIN QUERY PLAN']
}

export function sqlKeywords(dialect: SqlDialect): readonly string[] {
  return [...COMMON_KEYWORDS, ...DIALECT_KEYWORDS[dialect]]
}
