import { createHash } from 'node:crypto'
import { posix } from 'node:path'
import {
  IPV4_ONLY_LIBRARY_PATH,
  IPV4_ONLY_SOURCE,
  LEGACY_ASPNET_TARGETS,
  LEGACY_ASPNET_TARGETS_PATH,
  ORCA_EXEC_PATH,
  ORCA_EXEC_SCRIPT
} from './dotnet-container-assets'
import {
  CONTAINER_NETCOREDBG,
  DOTNET_CONTAINER_DOWNLOADS,
  type DotnetContainerArch
} from './dotnet-container-downloads'

// Why 20.04: .NET Core 3.1 needs OpenSSL 1.1, which later Ubuntu releases dropped.
const BASE_IMAGE =
  'ubuntu:20.04@sha256:8feb4d8ca5354def3d8fce243717141ce31e2c428701f6682bd2fafe15388214'

const APT_PACKAGES = [
  'ca-certificates',
  'curl',
  'libicu66',
  'libssl1.1',
  'libgssapi-krb5-2',
  'zlib1g',
  'libgdiplus',
  'tzdata',
  'fonts-noto-cjk',
  'procps'
]

/** The dotnet CLI's own home, so it never writes into the Mac's ~/.dotnet through the home mount. */
export const DOTNET_CONTAINER_CLI_HOME = '/var/lib/orca-dotnet'

const IMAGE_ENVIRONMENT = [
  'DOTNET_ROOT=/usr/share/dotnet',
  `DOTNET_CLI_HOME=${DOTNET_CONTAINER_CLI_HOME}`,
  'DOTNET_CLI_TELEMETRY_OPTOUT=1',
  'DOTNET_NOLOGO=1',
  'DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1',
  'DOTNET_GENERATE_ASPNET_CERTIFICATE=false',
  // Why: 2.x apps have no runtime here; Major lands them on 3.1.
  'DOTNET_ROLL_FORWARD=Major',
  `AfterMicrosoftNETSdkTargets=${LEGACY_ASPNET_TARGETS_PATH}`,
  `LD_PRELOAD=${IPV4_ONLY_LIBRARY_PATH}`
]

/** Base64 keeps quotes and `$` in the file out of the Dockerfile's shell. */
function writeFileCommand(path: string, content: string, mode: string): string {
  const encoded = Buffer.from(content, 'utf8').toString('base64')
  return `echo ${encoded} | base64 -d > ${path} && chmod ${mode} ${path}`
}

function downloadCommands(arch: DotnetContainerArch): string[] {
  return DOTNET_CONTAINER_DOWNLOADS[arch].map(
    (download) =>
      `curl -fsSL ${download.url} -o /tmp/dotnet.tgz` +
      ` && echo "${download.sha512}  /tmp/dotnet.tgz" | sha512sum -c -` +
      ' && tar -xzf /tmp/dotnet.tgz -C /usr/share/dotnet && rm /tmp/dotnet.tgz'
  )
}

/** Built with `docker build -` (no context), so every file it needs is inline. */
export function buildDotnetContainerDockerfile(arch: DotnetContainerArch): string {
  const continuation = ' \\\n && '
  return [
    "# Orca's .NET toolchain image; generated by dotnet-container-image.ts.",
    `FROM ${BASE_IMAGE} AS ipv4only`,
    'RUN apt-get update && apt-get install -y --no-install-recommends gcc libc6-dev' +
      ' && rm -rf /var/lib/apt/lists/*',
    `RUN ${writeFileCommand('/tmp/orca-ipv4only.c', IPV4_ONLY_SOURCE, '644')}` +
      ' && gcc -O2 -shared -fPIC -o /tmp/orca-ipv4only.so /tmp/orca-ipv4only.c -ldl',
    '',
    `FROM ${BASE_IMAGE}`,
    'ARG DEBIAN_FRONTEND=noninteractive',
    `RUN apt-get update && apt-get install -y --no-install-recommends ${APT_PACKAGES.join(' ')}` +
      ' && rm -rf /var/lib/apt/lists/*',
    `RUN mkdir -p /usr/share/dotnet${continuation}${downloadCommands(arch).join(continuation)}` +
      `${continuation}ln -s /usr/share/dotnet/dotnet /usr/local/bin/dotnet`,
    `RUN curl -fsSL ${CONTAINER_NETCOREDBG[arch].url} -o /tmp/netcoredbg.tgz` +
      ` && echo "${CONTAINER_NETCOREDBG[arch].sha256}  /tmp/netcoredbg.tgz" | sha256sum -c -` +
      ' && tar -xzf /tmp/netcoredbg.tgz -C /usr/local/lib && rm /tmp/netcoredbg.tgz',
    `COPY --from=ipv4only /tmp/orca-ipv4only.so ${IPV4_ONLY_LIBRARY_PATH}`,
    `RUN ${writeFileCommand(ORCA_EXEC_PATH, ORCA_EXEC_SCRIPT, '755')}` +
      `${continuation}mkdir -p ${posix.dirname(LEGACY_ASPNET_TARGETS_PATH)}` +
      `${continuation}${writeFileCommand(LEGACY_ASPNET_TARGETS_PATH, LEGACY_ASPNET_TARGETS, '644')}` +
      // Why 1777: the image is shared by every user; each run uses the host user's uid.
      `${continuation}mkdir -p ${DOTNET_CONTAINER_CLI_HOME} && chmod 1777 ${DOTNET_CONTAINER_CLI_HOME}`,
    `ENV ${IMAGE_ENVIRONMENT.join(' \\\n    ')}`,
    ''
  ].join('\n')
}

/** Content-addressed, so changing the Dockerfile builds a new image instead of reusing a stale one. */
export function dotnetContainerImageTag(dockerfile: string): string {
  return `orca-dotnet:${createHash('sha256').update(dockerfile).digest('hex').slice(0, 12)}`
}
