import { formatPosixCommand, quotePosixArg } from '../../shared/ssh-vpn-command-format'
import { ORCA_EXEC_PATH } from './dotnet-container-assets'
import { DOTNET_CONTAINER_CONFIG_LABEL, type DotnetContainerRun } from './dotnet-container-run'

export type DotnetContainerLauncherConfig = {
  dockerPath: string
  containerName: string
  image: string
  dockerfilePath: string
  platform: string
  mounts: readonly string[]
  run: DotnetContainerRun
  /** Docker Desktop's settings file, read to warn when host networking is off; null elsewhere. */
  dockerDesktopSettingsPath: string | null
  /** Where the host's ASP.NET development certificate is exported for HTTPS endpoints. */
  httpsCertificateDir: string
}

function mountCasePattern(mounts: readonly string[]): string {
  return mounts.map((mount) => `${quotePosixArg(mount)}/*`).join('|')
}

/**
 * The `dotnet` Orca's runs call: projects older than .NET 6 (or a global.json pinning SDK 3) go
 * to the container, everything else to the native SDK. POSIX sh: /bin/sh is bash on macOS and
 * dash on Debian-family Linux.
 */
export function buildDotnetContainerLauncher(config: DotnetContainerLauncherConfig): string {
  const runCommand = `"$orca_docker" ${formatPosixCommand(config.run.args)}`
  return `#!/bin/sh
# Generated by Orca (dotnet-container-launcher.ts); edits are overwritten.
orca_docker=${quotePosixArg(config.dockerPath)}
orca_container=${quotePosixArg(config.containerName)}
orca_image=${quotePosixArg(config.image)}
orca_config=${quotePosixArg(config.run.config)}
orca_dockerfile=${quotePosixArg(config.dockerfilePath)}
orca_platform=${quotePosixArg(config.platform)}
orca_mounts=${quotePosixArg(config.mounts.join(', '))}
orca_docker_settings=${quotePosixArg(config.dockerDesktopSettingsPath ?? '')}
orca_cert_dir=${quotePosixArg(config.httpsCertificateDir)}
orca_lock_dir="\${TMPDIR:-/tmp}/$orca_container.lock"
orca_legacy_tfm='<TargetFrameworks?>[^<]*(netcoreapp[0-9]|net5\\.0)'
# Why: docker exec otherwise ends a failed run with an ad for Docker Debug.
export DOCKER_CLI_HINTS=false

orca_fail() {
  printf 'orca: %s\\n' "$*" >&2
  exit 1
}

orca_self_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)

# Prints the first dotnet on PATH that is not this launcher.
orca_native_dotnet() {
  orca_ifs=$IFS
  IFS=:
  set -f
  orca_found=
  for orca_dir in $PATH; do
    if [ -n "$orca_dir" ] && [ "$orca_dir" != "$orca_self_dir" ] && [ -f "$orca_dir/dotnet" ] && [ -x "$orca_dir/dotnet" ]; then
      orca_found=$orca_dir/dotnet
      break
    fi
  done
  IFS=$orca_ifs
  set +f
  [ -n "$orca_found" ] && printf '%s\\n' "$orca_found"
}

orca_native() {
  orca_path=$(orca_native_dotnet) || orca_fail 'dotnet was not found on PATH'
  exec "$orca_path" "$@"
}

# Why: Kestrel's HTTPS endpoints need the development certificate, which lives in the Mac's
# keychain. The Mac already trusts it, so browsers accept what the container serves.
orca_prepare_https() {
  [ -z "\${ASPNETCORE_Kestrel__Certificates__Default__Path:-}" ] || return 0
  if ! orca_inside_mounts "$orca_cert_dir"; then
    printf 'orca: %s is not shared with the .NET container, so HTTPS endpoints have no certificate\\n' "$orca_cert_dir" >&2
    return 0
  fi
  orca_cert="$orca_cert_dir/aspnetcore-dev.pfx"
  # Why daily: dotnet dev-certs renews the Mac's certificate, and the copy has to follow it.
  if [ ! -f "$orca_cert" ] || [ -n "$(find "$orca_cert" -mtime +0 2>/dev/null)" ]; then
    orca_export_https_certificate
  fi
  if [ ! -f "$orca_cert" ]; then
    printf 'orca: could not export the HTTPS development certificate; HTTPS endpoints fail until "dotnet dev-certs https --trust" is run on this machine\\n' >&2
    return 0
  fi
  ASPNETCORE_Kestrel__Certificates__Default__Path=$orca_cert
  ASPNETCORE_Kestrel__Certificates__Default__Password=$(cat "$orca_cert_dir/password")
  export ASPNETCORE_Kestrel__Certificates__Default__Path ASPNETCORE_Kestrel__Certificates__Default__Password
}

# Replaces the certificate and its password together, so a failed export keeps the old pair.
orca_export_https_certificate() {
  orca_dev_certs=$(orca_native_dotnet) || return 1
  (
    umask 077
    # Why cd: a project's global.json can pin SDK 3.1, whose dev-certs wants sudo on macOS.
    mkdir -p "$orca_cert_dir" &&
      cd "$orca_cert_dir" &&
      od -An -N16 -tx1 /dev/urandom | tr -d ' \\n' > "$orca_cert_dir/password.new" &&
      "$orca_dev_certs" dev-certs https --export-path "$orca_cert.new" --password "$(cat "$orca_cert_dir/password.new")" >/dev/null 2>&1 &&
      mv "$orca_cert_dir/password.new" "$orca_cert_dir/password" &&
      mv "$orca_cert.new" "$orca_cert"
  )
}

orca_tree_has_legacy() {
  orca_found=$(find "$1" -maxdepth 3 \\( -name bin -o -name obj -o -name node_modules -o -name .git \\) -prune -o \\( -name '*.csproj' -o -name '*.fsproj' -o -name '*.vbproj' \\) -exec grep -Els "$orca_legacy_tfm" {} + 2>/dev/null | head -n 1)
  [ -n "$orca_found" ]
}

# The nearest global.json decides. Only SDK 3 pins: the image's one pre-6 SDK is 3.1.426.
orca_global_json_pins_legacy() {
  orca_dir=$1
  while :; do
    if [ -f "$orca_dir/global.json" ]; then
      grep -Eqs '"version"[[:space:]]*:[[:space:]]*"3\\.' "$orca_dir/global.json"
      return
    fi
    [ "$orca_dir" = / ] && return 1
    orca_dir=$(dirname -- "$orca_dir")
  done
}

orca_wants_container() {
  case "\${ORCA_DOTNET_TOOLCHAIN:-}" in
    container) return 0 ;;
    native) return 1 ;;
  esac
  if [ -d "$orca_target" ]; then orca_where=$orca_target; else orca_where=$(dirname -- "$orca_target"); fi
  orca_where=$(CDPATH= cd -- "$orca_where" 2>/dev/null && pwd -P) || return 1
  orca_global_json_pins_legacy "$orca_where" && return 0
  case "$orca_target" in
    *.csproj|*.fsproj|*.vbproj) [ -f "$orca_target" ] && grep -Eqs "$orca_legacy_tfm" "$orca_target" ;;
    *) orca_tree_has_legacy "$orca_where" ;;
  esac
}

orca_inside_mounts() {
  case "$1/" in
    ${mountCasePattern(config.mounts)}) return 0 ;;
  esac
  return 1
}

orca_warn_host_networking() {
  if [ -n "$orca_docker_settings" ] && grep -Eqs '"HostNetworkingEnabled"[[:space:]]*:[[:space:]]*false' "$orca_docker_settings"; then
    printf 'orca: Docker Desktop host networking is off, so localhost URLs and databases will not connect. Turn it on in Docker Desktop: Settings > Resources > Network.\\n' >&2
  fi
}

# Why a lock: compound runs start several launchers at once, and only one may create or replace.
orca_lock() {
  orca_waited=0
  orca_ownerless=0
  until mkdir "$orca_lock_dir" 2>/dev/null; do
    orca_holder=$(cat "$orca_lock_dir/pid" 2>/dev/null) || orca_holder=
    if [ -z "$orca_holder" ]; then orca_ownerless=$((orca_ownerless + 1)); else orca_ownerless=0; fi
    # Why: a launcher killed while holding the lock (or before naming itself) must not block later runs.
    if [ "$orca_ownerless" -gt 5 ] || { [ -n "$orca_holder" ] && ! ps -p "$orca_holder" >/dev/null 2>&1; }; then
      rm -rf "$orca_lock_dir"
      continue
    fi
    orca_waited=$((orca_waited + 1))
    [ "$orca_waited" -le 900 ] || orca_fail "timed out waiting for another run to prepare the .NET container (remove $orca_lock_dir if none is starting)"
    sleep 1
  done
  # Why exit on signals: dash skips the EXIT trap when a signal ends the shell.
  trap 'exit 130' HUP INT TERM
  trap 'rm -rf "$orca_lock_dir"' EXIT
  echo "$$" > "$orca_lock_dir/pid"
}

orca_unlock() {
  rm -rf "$orca_lock_dir"
  trap - EXIT
}

orca_container_state() {
  "$orca_docker" container inspect --format '{{.State.Running}} {{index .Config.Labels "${DOTNET_CONTAINER_CONFIG_LABEL}"}} {{len .ExecIDs}}' "$orca_container" 2>/dev/null
}

# Why: a launcher killed outright (SIGKILL, a crash) never runs its trap, so its program would
# keep running and holding its port. Run IDs start with the launcher's PID.
orca_reap_orphans() {
  for orca_id in $("$orca_docker" exec "$orca_container" ${ORCA_EXEC_PATH} --list 2>/dev/null); do
    ps -p "\${orca_id%%.*}" >/dev/null 2>&1 || "$orca_docker" exec "$orca_container" ${ORCA_EXEC_PATH} --kill "$orca_id" >/dev/null 2>&1
  done
}

orca_create_container() {
  if ! "$orca_docker" image inspect "$orca_image" >/dev/null 2>&1; then
    printf 'orca: building the .NET container image; the first time takes a few minutes\\n' >&2
    "$orca_docker" build --platform "$orca_platform" --tag "$orca_image" - < "$orca_dockerfile" >&2 ||
      orca_fail 'could not build the .NET container image'
  fi
  orca_error=$(${runCommand} 2>&1 >/dev/null) || orca_fail "could not start the .NET container: $orca_error"
}

orca_prepare_container() {
  orca_state=$(orca_container_state) || orca_state=
  case "$orca_state" in
    true\\ *)
      orca_reap_orphans
      orca_state=$(orca_container_state) || orca_state=
      ;;
  esac
  case "$orca_state" in
    "true $orca_config "*) return 0 ;;
    "false $orca_config "*)
      orca_error=$("$orca_docker" start "$orca_container" 2>&1 >/dev/null) || orca_fail "could not start the .NET container: $orca_error"
      return 0
      ;;
    true\\ *\\ 0) "$orca_docker" rm --force "$orca_container" >/dev/null 2>&1 ;;
    true\\ *)
      printf 'orca: the .NET container is out of date; it is replaced once the programs running in it exit\\n' >&2
      return 0
      ;;
    ?*) "$orca_docker" rm --force "$orca_container" >/dev/null 2>&1 ;;
  esac
  orca_create_container
}

case "\${1:-}" in
  ''|-*|dev-certs|workload|sdk|help) orca_native "$@" ;;
esac

orca_target=.
orca_prev=
for orca_arg in "$@"; do
  case "$orca_prev" in
    --project|-p) [ -e "$orca_arg" ] && orca_target=$orca_arg ;;
  esac
  case "$orca_arg" in
    --project=*) orca_target=\${orca_arg#--project=} ;;
    *.csproj|*.fsproj|*.vbproj|*.sln|*.slnx|*.slnf) [ -e "$orca_arg" ] && orca_target=$orca_arg ;;
  esac
  orca_prev=$orca_arg
done

orca_wants_container || orca_native "$@"

orca_cwd=$(pwd -P)
orca_inside_mounts "$orca_cwd" ||
  orca_fail "$orca_cwd is outside the folders shared with the .NET container: $orca_mounts"
command -v "$orca_docker" >/dev/null 2>&1 || orca_fail 'Docker was not found. Install Docker Desktop to run .NET 5 and older projects.'
"$orca_docker" info >/dev/null 2>&1 || orca_fail 'Docker is not running. Start Docker Desktop, then run this again.'
orca_warn_host_networking
orca_lock
orca_prepare_container
orca_prepare_https
orca_unlock

orca_env_flags=
for orca_name in $(env | sed -n \\
  -e 's/^\\(ASPNETCORE_[A-Za-z0-9_]*\\)=.*/\\1/p' \\
  -e 's/^\\([A-Za-z_][A-Za-z0-9_]*__[A-Za-z0-9_]*\\)=.*/\\1/p' \\
  -e 's/^\\(DOTNET_ENVIRONMENT\\)=.*/\\1/p' \\
  -e 's/^\\(TERM\\)=.*/\\1/p' \\
  -e 's/^\\(COLORTERM\\)=.*/\\1/p' \\
  -e 's/^\\(LANG\\)=.*/\\1/p' \\
  -e 's/^\\(LC_ALL\\)=.*/\\1/p'); do
  orca_env_flags="$orca_env_flags -e $orca_name"
done

orca_run_id="$$.$(date +%s)"
orca_tty=
if [ -t 0 ] && [ -t 1 ]; then orca_tty=-t; fi
orca_child=
orca_stop() {
  "$orca_docker" exec "$orca_container" ${ORCA_EXEC_PATH} --kill "$orca_run_id" >/dev/null 2>&1
  if [ -n "$orca_child" ]; then kill "$orca_child" 2>/dev/null; fi
}
# Why: a closed pane or a killed client leaves the program running inside the container.
trap orca_stop HUP INT TERM
# Why fd 3: dash points a background command's stdin at /dev/null before its own redirections.
exec 3<&0
# Why background + wait: a trap only runs once the foreground command ends.
"$orca_docker" exec -i $orca_tty -w "$orca_cwd" $orca_env_flags "$orca_container" ${ORCA_EXEC_PATH} "$orca_run_id" dotnet "$@" <&3 3<&- &
orca_child=$!
while :; do
  wait "$orca_child"
  orca_status=$?
  kill -0 "$orca_child" 2>/dev/null || break
done
exit "$orca_status"
`
}
