import { quotePosixArg } from '../../shared/ssh-vpn-command-format'
import { ORCA_EXEC_PATH } from './dotnet-container-assets'
import {
  containerLifecycleFunctions,
  httpsCertificateFunctions
} from './dotnet-container-launcher-lifecycle'
import type { DotnetContainerRun } from './dotnet-container-run'

export type DotnetContainerLauncherConfig = {
  dockerPath: string
  containerName: string
  image: string
  dockerfilePath: string
  platform: string
  mounts: readonly string[]
  run: DotnetContainerRun
  /** Docker Desktop's settings file, read to warn when host networking is off; null elsewhere. */
  dockerDesktopSettingsPath: string | null
  /** Where the host's ASP.NET development certificate is exported for HTTPS endpoints. */
  httpsCertificateDir: string
}

function mountCasePattern(mounts: readonly string[]): string {
  return mounts.map((mount) => `${quotePosixArg(mount)}/*`).join('|')
}

/**
 * The `dotnet` Orca's runs call: projects older than .NET 6 (or a global.json pinning SDK 3) go
 * to the container, everything else to the native SDK. POSIX sh: /bin/sh is bash on macOS and
 * dash on Debian-family Linux.
 */
export function buildDotnetContainerLauncher(config: DotnetContainerLauncherConfig): string {
  return `#!/bin/sh
# Generated by Orca (dotnet-container-launcher.ts); edits are overwritten.
orca_docker=${quotePosixArg(config.dockerPath)}
orca_container=${quotePosixArg(config.containerName)}
orca_image=${quotePosixArg(config.image)}
orca_config=${quotePosixArg(config.run.config)}
orca_dockerfile=${quotePosixArg(config.dockerfilePath)}
orca_platform=${quotePosixArg(config.platform)}
orca_mounts=${quotePosixArg(config.mounts.join(', '))}
orca_docker_settings=${quotePosixArg(config.dockerDesktopSettingsPath ?? '')}
orca_cert_dir=${quotePosixArg(config.httpsCertificateDir)}
orca_lock_dir="\${TMPDIR:-/tmp}/$orca_container.lock"
orca_legacy_tfm='<TargetFrameworks?>[^<]*(netcoreapp[0-9]|net5\\.0)'
# Why: docker exec otherwise ends a failed run with an ad for Docker Debug.
export DOCKER_CLI_HINTS=false

orca_fail() {
  printf 'orca: %s\\n' "$*" >&2
  exit 1
}

orca_self_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)

# Prints the first dotnet on PATH that is not this launcher.
orca_native_dotnet() {
  orca_ifs=$IFS
  IFS=:
  set -f
  orca_found=
  for orca_dir in $PATH; do
    if [ -n "$orca_dir" ] && [ "$orca_dir" != "$orca_self_dir" ] && [ -f "$orca_dir/dotnet" ] && [ -x "$orca_dir/dotnet" ]; then
      orca_found=$orca_dir/dotnet
      break
    fi
  done
  IFS=$orca_ifs
  set +f
  [ -n "$orca_found" ] && printf '%s\\n' "$orca_found"
}

orca_native() {
  orca_path=$(orca_native_dotnet) || orca_fail 'dotnet was not found on PATH'
  exec "$orca_path" "$@"
}

${httpsCertificateFunctions()}

orca_tree_has_legacy() {
  orca_found=$(find "$1" -maxdepth 3 \\( -name bin -o -name obj -o -name node_modules -o -name .git \\) -prune -o \\( -name '*.csproj' -o -name '*.fsproj' -o -name '*.vbproj' \\) -exec grep -Els "$orca_legacy_tfm" {} + 2>/dev/null | head -n 1)
  [ -n "$orca_found" ]
}

# The nearest global.json decides. Only SDK 3 pins: the image's one pre-6 SDK is 3.1.426.
orca_global_json_pins_legacy() {
  orca_dir=$1
  while :; do
    if [ -f "$orca_dir/global.json" ]; then
      grep -Eqs '"version"[[:space:]]*:[[:space:]]*"3\\.' "$orca_dir/global.json"
      return
    fi
    [ "$orca_dir" = / ] && return 1
    orca_dir=$(dirname -- "$orca_dir")
  done
}

orca_wants_container() {
  case "\${ORCA_DOTNET_TOOLCHAIN:-}" in
    container) return 0 ;;
    native) return 1 ;;
  esac
  if [ -d "$orca_target" ]; then orca_where=$orca_target; else orca_where=$(dirname -- "$orca_target"); fi
  orca_where=$(CDPATH= cd -- "$orca_where" 2>/dev/null && pwd -P) || return 1
  orca_global_json_pins_legacy "$orca_where" && return 0
  case "$orca_target" in
    *.csproj|*.fsproj|*.vbproj) [ -f "$orca_target" ] && grep -Eqs "$orca_legacy_tfm" "$orca_target" ;;
    *) orca_tree_has_legacy "$orca_where" ;;
  esac
}

orca_inside_mounts() {
  case "$1/" in
    ${mountCasePattern(config.mounts)}) return 0 ;;
  esac
  return 1
}

${containerLifecycleFunctions(config.run.args)}

# Modes besides plain \`dotnet ...\`: --orca-where prints where a command would run, --orca-ensure
# only prepares the container, --orca-exec and --orca-shell run something else in it.
orca_mode=dotnet
case "\${1:-}" in
  --orca-where|--orca-ensure|--orca-exec|--orca-shell)
    orca_mode=\${1#--orca-}
    shift
    ;;
esac

if [ "$orca_mode" = dotnet ] || [ "$orca_mode" = where ]; then
  case "\${1:-}" in
    ''|-*|dev-certs|workload|sdk|help) orca_target= ;;
    *)
      orca_target=.
      orca_startup=
      orca_prev=
      for orca_arg in "$@"; do
        case "$orca_prev" in
          --project|-p) [ -e "$orca_arg" ] && orca_target=$orca_arg ;;
          --startup-project|-s) [ -e "$orca_arg" ] && orca_startup=$orca_arg ;;
        esac
        case "$orca_arg" in
          --project=*) orca_target=\${orca_arg#--project=} ;;
          --startup-project=*) orca_startup=\${orca_arg#--startup-project=} ;;
          *.csproj|*.fsproj|*.vbproj|*.sln|*.slnx|*.slnf) [ -e "$orca_arg" ] && orca_target=$orca_arg ;;
        esac
        orca_prev=$orca_arg
      done
      # Why: EF runs on the startup project's runtime (default: the current folder's project), and
      # --project is often a netstandard library. Elsewhere -s means --source.
      [ "$1" != ef ] || orca_target=\${orca_startup:-.}
      ;;
  esac
  if [ -n "$orca_target" ] && orca_wants_container; then orca_where=container; else orca_where=native; fi
  if [ "$orca_mode" = where ]; then
    echo "$orca_where"
    exit 0
  fi
  [ "$orca_where" = container ] || orca_native "$@"
  set -- dotnet "$@"
fi
case "$orca_mode" in
  exec) [ $# -gt 0 ] || orca_fail '--orca-exec needs a program to run' ;;
  shell) set -- env 'PS1=(.NET container) \\w \\$ ' bash --noprofile --norc ;;
esac

orca_cwd=$(pwd -P)
orca_inside_mounts "$orca_cwd" ||
  orca_fail "$orca_cwd is outside the folders shared with the .NET container: $orca_mounts"
command -v "$orca_docker" >/dev/null 2>&1 || orca_fail 'Docker was not found. Install Docker Desktop to run .NET 5 and older projects.'
"$orca_docker" info >/dev/null 2>&1 || orca_fail 'Docker is not running. Start Docker Desktop, then run this again.'
orca_warn_host_networking
orca_lock
orca_prepare_container
orca_prepare_https
orca_unlock
[ "$orca_mode" = ensure ] && exit 0

orca_env_flags=
for orca_name in $(env | sed -n \\
  -e 's/^\\(ASPNETCORE_[A-Za-z0-9_]*\\)=.*/\\1/p' \\
  -e 's/^\\([A-Za-z_][A-Za-z0-9_]*__[A-Za-z0-9_]*\\)=.*/\\1/p' \\
  -e 's/^\\(DOTNET_ENVIRONMENT\\)=.*/\\1/p' \\
  -e 's/^\\(TERM\\)=.*/\\1/p' \\
  -e 's/^\\(COLORTERM\\)=.*/\\1/p' \\
  -e 's/^\\(LANG\\)=.*/\\1/p' \\
  -e 's/^\\(LC_ALL\\)=.*/\\1/p'); do
  orca_env_flags="$orca_env_flags -e $orca_name"
done

orca_run_id="$$.$(date +%s)"
orca_tty=
if [ -t 0 ] && [ -t 1 ]; then orca_tty=-t; fi
orca_child=
orca_stop() {
  "$orca_docker" exec "$orca_container" ${ORCA_EXEC_PATH} --kill "$orca_run_id" >/dev/null 2>&1
  if [ -n "$orca_child" ]; then kill "$orca_child" 2>/dev/null; fi
}
# Why: a closed pane or a killed client leaves the program running inside the container.
trap orca_stop HUP INT TERM
# Why fd 3: dash points a background command's stdin at /dev/null before its own redirections.
exec 3<&0
# Why background + wait: a trap only runs once the foreground command ends.
"$orca_docker" exec -i $orca_tty -w "$orca_cwd" $orca_env_flags "$orca_container" ${ORCA_EXEC_PATH} "$orca_run_id" "$@" <&3 3<&- &
orca_child=$!
while :; do
  wait "$orca_child"
  orca_status=$?
  kill -0 "$orca_child" 2>/dev/null || break
done
# Why: a crashed debugger or a dead docker client ends the exec but not what it started.
"$orca_docker" exec "$orca_container" ${ORCA_EXEC_PATH} --kill "$orca_run_id" </dev/null >/dev/null 2>&1
exit "$orca_status"
`
}
