import type pg from 'pg'
import type {
  DatabaseObjectProperties,
  DatabasePropertiesTarget,
  DatabasePropertySection
} from '../../../shared/database/database-properties-types'
import { optionalRead, property, propertyText } from './database-property-values'

type Row = Record<string, unknown>

const RELATION_TYPES: Record<string, string> = {
  r: 'table',
  p: 'partitioned table',
  v: 'view',
  m: 'materialized view',
  f: 'foreign table'
}
const PERSISTENCE: Record<string, string> = { p: 'permanent', u: 'unlogged', t: 'temporary' }

async function rowsOf(client: pg.Client, sql: string, values: unknown[] = []): Promise<Row[]> {
  return (await client.query<Row>(sql, values)).rows
}

function databaseSql(version: number): string {
  const provider =
    version >= 150_000
      ? `case d.datlocprovider when 'c' then 'libc' when 'i' then 'icu' when 'b' then 'builtin' end`
      : 'null'
  const locale = version >= 170_000 ? 'd.datlocale' : version >= 150_000 ? 'd.daticulocale' : 'null'
  return `
    select pg_catalog.pg_get_userbyid(d.datdba) as owner,
           pg_catalog.pg_encoding_to_char(d.encoding) as encoding,
           d.datcollate as collation, d.datctype as ctype,
           ${provider} as locale_provider, ${locale} as locale, t.spcname as tablespace,
           nullif(d.datconnlimit, -1) as connection_limit, d.datallowconn as allow_connections,
           d.datistemplate as is_template,
           pg_catalog.shobj_description(d.oid, 'pg_database') as comment
    from pg_catalog.pg_database d
    left join pg_catalog.pg_tablespace t on t.oid = d.dattablespace
    where d.datname = $1`
}

const SCHEMA_SQL = `
  select pg_catalog.pg_get_userbyid(n.nspowner) as owner,
         pg_catalog.obj_description(n.oid, 'pg_namespace') as comment,
         (select count(*) from pg_catalog.pg_class c
          where c.relnamespace = n.oid and c.relkind in ('r', 'p')) as table_count
  from pg_catalog.pg_namespace n where n.nspname = $1`

function relationSql(version: number): string {
  const partitions = version >= 100_000
  return `
    select c.oid, c.relkind, c.relpersistence, pg_catalog.pg_get_userbyid(c.relowner) as owner,
           t.spcname as tablespace, pg_catalog.array_to_string(c.reloptions, ', ') as options,
           c.reltuples::bigint as reltuples, c.relrowsecurity as row_security,
           c.relispopulated as populated, pg_catalog.obj_description(c.oid, 'pg_class') as comment,
           ${version >= 120_000 ? 'am.amname' : 'null'} as access_method,
           ${partitions ? `case when c.relkind = 'p' then pg_catalog.pg_get_partkeydef(c.oid) end` : 'null'} as partition_key,
           ${partitions ? '(select i.inhparent::pg_catalog.regclass::text from pg_catalog.pg_inherits i where i.inhrelid = c.oid and c.relispartition limit 1)' : 'null'} as partition_of
    from pg_catalog.pg_class c
    join pg_catalog.pg_namespace n on n.oid = c.relnamespace
    left join pg_catalog.pg_tablespace t on t.oid = c.reltablespace
    ${version >= 120_000 ? 'left join pg_catalog.pg_am am on am.oid = c.relam' : ''}
    where n.nspname = $1 and c.relname = $2 and c.relkind in ('r', 'p', 'v', 'm', 'f')`
}

const SIZES_SQL = `
  select pg_catalog.pg_table_size($1::oid) as data, pg_catalog.pg_indexes_size($1::oid) as indexes,
         pg_catalog.pg_total_relation_size($1::oid) as total`

function columnsSql(version: number): string {
  const expression = 'pg_catalog.pg_get_expr(d.adbin, d.adrelid)'
  const generated =
    version >= 120_000
      ? `case when a.attgenerated = 's' then 'GENERATED ALWAYS AS (' || ${expression} || ') STORED' else ${expression} end`
      : expression
  const identity =
    version >= 100_000
      ? `case a.attidentity when 'a' then 'GENERATED ALWAYS AS IDENTITY' when 'd' then 'GENERATED BY DEFAULT AS IDENTITY' end`
      : 'null'
  return `
    select a.attname as name, pg_catalog.format_type(a.atttypid, a.atttypmod) as data_type,
           not a.attnotnull as nullable, coalesce(${identity}, ${generated}) as default_value,
           case when a.attcollation <> 0 and a.attcollation <> ty.typcollation
                then co.collname end as collation,
           pg_catalog.col_description(a.attrelid, a.attnum) as comment
    from pg_catalog.pg_attribute a
    join pg_catalog.pg_type ty on ty.oid = a.atttypid
    left join pg_catalog.pg_attrdef d on d.adrelid = a.attrelid and d.adnum = a.attnum
    left join pg_catalog.pg_collation co on co.oid = a.attcollation
    where a.attrelid = $1::oid and a.attnum > 0 and not a.attisdropped
    order by a.attnum`
}

async function databaseSection(
  client: pg.Client,
  database: string,
  version: number,
  notes: string[]
): Promise<DatabasePropertySection> {
  const [row] = await rowsOf(client, databaseSql(version), [database])
  if (!row) {
    throw new Error(`Database ${database} was not found.`)
  }
  // Why optional: pg_database_size needs CONNECT on that database.
  const [size] =
    (await optionalRead(notes, 'size', () =>
      rowsOf(client, 'select pg_catalog.pg_database_size($1) as size', [database])
    )) ?? []
  return {
    kind: 'database',
    name: database,
    properties: [
      ...property('owner', row.owner),
      ...property('encoding', row.encoding),
      ...property('collation', row.collation),
      ...property('ctype', row.ctype),
      ...property('localeProvider', row.locale_provider),
      ...property('locale', row.locale),
      ...property('tablespace', row.tablespace),
      ...property('connectionLimit', row.connection_limit, 'count'),
      ...property('allowConnections', row.allow_connections, 'boolean'),
      ...property('isTemplate', row.is_template, 'boolean'),
      ...property('size', size?.size, 'bytes'),
      ...property('comment', row.comment)
    ]
  }
}

async function serverProperties(
  client: pg.Client,
  version: number,
  notes: string[]
): Promise<DatabaseObjectProperties> {
  const [row] = await rowsOf(
    client,
    `select pg_catalog.current_setting('server_version') as version,
            pg_catalog.current_setting('TimeZone') as time_zone,
            pg_catalog.current_database() as current_database`
  )
  const server: DatabasePropertySection = {
    kind: 'server',
    name: null,
    properties: [...property('version', row?.version), ...property('timeZone', row?.time_zone)]
  }
  const database = await databaseSection(client, String(row?.current_database), version, notes)
  return { sections: [server, database], columns: null, notes }
}

async function schemaProperties(
  client: pg.Client,
  schema: string,
  notes: string[]
): Promise<DatabaseObjectProperties> {
  const [row] = await rowsOf(client, SCHEMA_SQL, [schema])
  if (!row) {
    throw new Error(`Schema ${schema} was not found.`)
  }
  const properties = [
    ...property('owner', row.owner),
    ...property('tableCount', row.table_count, 'count'),
    ...property('comment', row.comment)
  ]
  return { sections: [{ kind: 'schema', name: schema, properties }], columns: null, notes }
}

function relationEntries(row: Row, sizes: Row | undefined): DatabasePropertySection['properties'] {
  const kind = String(row.relkind)
  const stored = kind === 'r' || kind === 'p' || kind === 'm'
  const reltuples = Number(row.reltuples)
  return [
    ...property('type', RELATION_TYPES[kind]),
    ...property('owner', row.owner),
    ...(stored ? property('persistence', PERSISTENCE[String(row.relpersistence)]) : []),
    ...property('accessMethod', row.access_method),
    ...property('tablespace', row.tablespace),
    ...property('options', row.options),
    ...property('partitionKey', row.partition_key),
    ...property('partitionOf', row.partition_of),
    ...(kind === 'r' || kind === 'p' ? property('rowSecurity', row.row_security, 'boolean') : []),
    ...(kind === 'm' ? property('populated', row.populated, 'boolean') : []),
    // Why ≥ 0: -1 means never analyzed (PostgreSQL 14 and later).
    ...(stored && reltuples >= 0 ? property('rowsEstimate', row.reltuples, 'count') : []),
    ...property('dataSize', sizes?.data, 'bytes'),
    ...property('indexSize', sizes?.indexes, 'bytes'),
    ...property('size', sizes?.total, 'bytes'),
    ...property('comment', row.comment)
  ]
}

async function relationProperties(
  client: pg.Client,
  schema: string,
  relation: string,
  version: number,
  notes: string[]
): Promise<DatabaseObjectProperties> {
  const [row] = await rowsOf(client, relationSql(version), [schema, relation])
  if (!row) {
    throw new Error(`Table ${schema}.${relation} was not found.`)
  }
  const kind = String(row.relkind)
  const stored = kind === 'r' || kind === 'p' || kind === 'm'
  const [sizes] = stored
    ? ((await optionalRead(notes, 'sizes', () => rowsOf(client, SIZES_SQL, [row.oid]))) ?? [])
    : []
  const columns = await rowsOf(client, columnsSql(version), [row.oid])
  return {
    sections: [
      {
        kind: kind === 'v' || kind === 'm' ? 'view' : 'table',
        name: relation,
        properties: relationEntries(row, sizes)
      }
    ],
    columns: columns.map((column) => ({
      name: String(column.name),
      dataType: String(column.data_type),
      nullable: column.nullable === true,
      defaultValue: propertyText(column.default_value),
      characterSet: null,
      collation: propertyText(column.collation),
      comment: propertyText(column.comment)
    })),
    notes
  }
}

/** `client` is on the database the target names; pg_database is shared, so any reads it. */
export async function postgresProperties(
  client: pg.Client,
  target: DatabasePropertiesTarget,
  version: number
): Promise<DatabaseObjectProperties> {
  const notes: string[] = []
  switch (target.kind) {
    case 'server':
      return serverProperties(client, version, notes)
    case 'database': {
      const section = await databaseSection(client, target.database, version, notes)
      return { sections: [section], columns: null, notes }
    }
    case 'schema':
      return schemaProperties(client, target.schema, notes)
    case 'relation':
      return relationProperties(client, target.schema, target.relation, version, notes)
  }
}
